### ISSUE TITLE
'type: module' Missing from configuration suggestion in HACS

### ISSUE THREAD

**Issue by gregcsw** [custom-cards/monster-card#2]
When using HACS to install/maintain the custom card

The configuration suggestion is missing 'type: module/js' resulting in the card not working.

Shows:
```
When you add this to your configuration use this: 
  - url: /community_plugin/monster-card/monster-card.js
```
Should be:
```
When you add this to your configuration use this: 
  - url: /community_plugin/monster-card/monster-card.js
    type: module
```

I reported this to Ludees, whose response was:

> hacs does not know this, where it show is where the dev has added it to the readme of that repo, hacs looks in that file for a clue, if it can't find it it will not suggest anything, since there is a 50% chance of it being wrong. Untill the dev updates the readme of those repos it will not show.

Same problem with the below cards:
- group-card
- monster-card
- beer-card
- bignumber-card
- entity-attributes-card
- gauge-card
- home-setter
- plan-coordinates

**Comment by Flying-Ace** [comment]
omg i spent hours racking my brain only to find out this was reported but not fixed completely. :(
hacs still pulls from the readme and did not pickup the updated install sxn 
   the updated install sxn does not appear to be published. the readme on the main page ends after the 
   "Supports both inclusion and exclusion filters with wildcard for entity_ids." sxn.  the install sxn after that sxn is not there.

 
type: module
or 
type: js

**Comment by ludeeus** [comment]
When in doubt try module,if that fails try js.
