### ISSUE TITLE
Monster Card now showing in lovelace

### ISSUE THREAD

**Issue by jfgjesus** [custom-cards/monster-card#5]
I have installed the custom card with the HACS. 

I added the text:
"resources:
  - url: /community_plugin/monster-card/monster-card.js"

It worked for 1 hour but now, after restarting hassio,  I get a red card in lovelace saying "custom element does not exist: monster-card ....."

**Comment by jfgjesus** [comment]
It was missigin the "type: module" in lovelace raw config. i was not said in HACS descriptions.

**Comment by platini76** [comment]
no luck here...
my directory is:
/home/homeassistant/.homeassistant/www/community/monster-card

I tried all config:

 - url: /community/monster-card/monster-card.js
    type: module

 - url: /local/community/monster-card/monster-card.js
    type: module

no luck.. any suggestions?

**Comment by jfgjesus** [comment]
> no luck here...
> my directory is:
> /home/homeassistant/.homeassistant/www/community/monster-card
> 
> I tried all config:
> 
> * url: /community/monster-card/monster-card.js
>   type: module
> * url: /local/community/monster-card/monster-card.js
>   type: module
> 
> no luck.. any suggestions?


I used:
  - type: module
    url: /community_plugin/monster-card/monster-card.js

**Comment by platini76** [comment]
no it don't works!

**Comment by platini76** [comment]
which file you use for config?

**Comment by jfgjesus** [comment]
I write it on the lovelace "RAW config editor", at the beginning of the file, under "resources :"

**Comment by Midnitte** [comment]
Also can't get it to show, I downloaded the file and place it in /www/. Inside my RAW config for lovelace I have tried both
```
  - type: module
    url: /local/monster-card.js
```
and
```
  - type: js
    url: /local/monster-card.js
```
I only get 

> Custom element doesn't exist: monster-card.

**Comment by Adams-Scott** [comment]
If you are editing a single card instead of the whole lovelace config file, be sure to not use the hyphen. It should be:

      type: custom:monster-card
      card:
        type: glance
        title: Monster
      filter:
        include:...

not:

    - type: custom:monster-card
      card:
        type: glance
        title: Monster
      filter:
        include:...
